sources:
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
      - name: customers
      - name: nations
      - name: regions
      - name: orders
        config:
          freshness:
            warn_after: {count: 10, period: day}
            error_after: {count: 10, period: day}
          loaded_at_field: o_orderdate::timestamp_ntz
      - name: lineitems
      - name : suppliers
      - name : partsupps
      - name: parts


  - name: src_mkmotors
    database: mkmotors_dev
    schema: staging
    tables:
      - name: stg_employees

  - name: src3
    database: analytics
    schema: dbt_bhabna
    tables:
      - name: stg_employee